"use client";

import { useActionState, useState } from "react";
import { BedDouble, Plus, Save } from "lucide-react";
import { createRoom } from "@/app/admin/rooms/actions";
import type { SettingsActionState } from "@/types/settings";

export function NewRoomForm({ nextNumbers }: { nextNumbers: Record<number, number> }) {
  const floors = Object.keys(nextNumbers).map(Number).sort((a,b) => b-a);
  const [floor, setFloor] = useState(floors[0] ?? 1);
  const [state, action, pending] = useActionState(createRoom, null as SettingsActionState);
  const nextNumber = nextNumbers[floor] ?? floor * 100 + 1;

  return <details className="panel group mb-6 overflow-hidden"><summary className="flex cursor-pointer list-none items-center gap-3 bg-[#173545] px-5 py-4 text-white"><span className="grid size-9 place-items-center rounded-lg bg-white/10"><Plus size={20}/></span><div><p className="text-[9px] font-bold tracking-[.16em] text-slate-300">YENİ KAYIT</p><h2 className="font-display text-lg font-extrabold">Yeni oda ekle</h2></div><span className="ml-auto rounded-lg bg-white/10 px-3 py-2 text-xs font-bold">Sıradaki: {nextNumber}</span></summary><form action={action} className="p-5"><div className="mb-4 flex items-start gap-2 rounded-lg border border-sky-100 bg-sky-50 p-3 text-xs leading-5 text-sky-800"><BedDouble className="mt-0.5 shrink-0" size={16}/>Oda numarası otomatik belirlenir ve değiştirilemez. Seçilen kattaki son odanın devamı kullanılır; yeni oda başlangıçta her zaman <b>Boş</b> olur.</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="form-field"><span>KAT</span><select name="floor" value={floor} onChange={event => setFloor(Number(event.target.value))}>{floors.map(value => <option key={value} value={value}>{value}. Kat — yeni oda {nextNumbers[value]}</option>)}</select></label><label className="form-field"><span>OTOMATİK ODA NUMARASI</span><input value={nextNumber} disabled className="font-bold"/></label><label className="form-field"><span>KAPASİTE</span><input name="capacity" type="number" min={1} max={20} required placeholder="Kişi sayısı"/></label><label className="form-field"><span>KONAKLAMA TÜRÜ</span><select name="rentalType" defaultValue="daily"><option value="daily">Günlük</option><option value="monthly">Aylık</option></select></label><label className="form-field sm:col-span-2"><span>YATAK / ODA ÖZELLİĞİ</span><input name="bedInfo" required minLength={2} placeholder="Örn. 1 duble + 1 tekli yatak"/></label><label className="form-field sm:col-span-2"><span>FİYAT</span><input name="rate" required placeholder="Örn. 2.500 ₺ / gece veya 15.000 ₺ / ay"/></label><label className="form-field sm:col-span-2 lg:col-span-4"><span>AÇIKLAMA / NOT <em>İsteğe bağlı</em></span><textarea name="note" rows={2} placeholder="Odayla ilgili özel bilgiler"/></label>{state?.error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700 sm:col-span-2 lg:col-span-4">{state.error}</p>}{state?.success && <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700 sm:col-span-2 lg:col-span-4">{state.success}</p>}<div className="flex justify-end sm:col-span-2 lg:col-span-4"><button disabled={pending} className="flex items-center gap-2 rounded-lg bg-[#287da5] px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><Save size={16}/>{pending ? "Oluşturuluyor..." : `${nextNumber} numaralı odayı ekle`}</button></div></div></form></details>;
}

