import { Check, Clock3, UserCheck, X } from "lucide-react";
import { setReceptionApproval } from "@/app/auth/actions";
import { LogoutButton } from "@/components/auth/LogoutButton";
import type { UserProfile } from "@/types/auth";

const labels = { pending: "Onay bekliyor", approved: "Onaylı", rejected: "Reddedildi" } as const;

export function UserApprovalPanel({ users }: { users: UserProfile[] }) {
  return <section className="border-b border-slate-200 bg-white px-5 py-5 md:px-8"><div className="mx-auto max-w-[1500px]"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold tracking-[.16em] text-slate-400">KULLANICI YÖNETİMİ</p><h1 className="font-display text-xl font-extrabold text-[#173545]">Resepsiyon hesapları</h1></div><LogoutButton/></div><div className="mt-4 grid gap-3 lg:grid-cols-2 xl:grid-cols-3">{users.length === 0 && <p className="text-sm text-slate-500">Henüz resepsiyon hesabı yok.</p>}{users.map(user => <article key={user.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-bold text-slate-800">{user.full_name || "İsimsiz kullanıcı"}</p><p className="truncate text-xs text-slate-500">{user.email}</p></div><span className="flex shrink-0 items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{user.approval_status === "pending" ? <Clock3 size={12}/> : <UserCheck size={12}/>} {labels[user.approval_status]}</span></div><div className="mt-4 flex gap-2"><form action={setReceptionApproval}><input type="hidden" name="userId" value={user.id}/><input type="hidden" name="status" value="approved"/><button className="flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><Check size={14}/>Onayla</button></form><form action={setReceptionApproval}><input type="hidden" name="userId" value={user.id}/><input type="hidden" name="status" value="rejected"/><button className="flex items-center gap-1 rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700"><X size={14}/>Reddet</button></form></div></article>)}</div></div></section>;
}
